### PR TITLE
Add Angular 19 Support 

### PR DESCRIPTION
**Pull request by EphraimHaber**
this pr contains the necessary minimal changes to support angular 19.

### CODE REVIEW

**Comment by EphraimHaber** [comment]
closes #166

**Comment by EphraimHaber** [comment]
Note: I did not modify the version of the package. This should be done by a core maintainer before the next release to NPM.

**Comment by uap-universe** [comment]
Hi @EphraimHaber 
thank you for the PR.

Have you already performed the regression tests for integrating the updated smart table package in an Angular 16, 17, 18 project?

**Comment by EphraimHaber** [comment]
Hi @uap-universe 
Can you explain please? I've built the .tgz and tested it on a new project. Working nicely as expected.

**Comment by EphraimHaber** [comment]
Ah ok. Clever. I have not run them. but I'm not sure it's possible to do that given the changes the angular team has made to the `@component` decorator. I will try and do it by the end of the day.

@uap-universe

**Review by uap-universe — APPROVED** [review]
The `standalone` flag was already present in all still supported Angular versions. So this is good to go to be merged into the next release.

**Pull request merged**
