### PR TITLE
Export to csv feature enabled as table property.

### PR DESCRIPTION
**Pull request by dj-fiorex**

### CODE REVIEW

**Comment by dj-fiorex** [comment]
I looked at the PR but i want to use a more complex library (maybe PapaParse) to export data to csv, would you like to clone this repo and try to do it @Rj-saini ?

**Comment by hexdecimal16** [comment]
@dj-fiorex maybe it's better if it's handled outside library as it will allow user the freedom to use any method of exporting they like

**Comment by dj-fiorex** [comment]
I think you are right, this is a table, so it's not his work!

**Comment by hexdecimal16** [comment]
> it's handled outside library as it will allow user the freedom to use any method of exporting they like

we can close it now

**Pull request closed without merging**
